name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
            role-to-assume: arn:aws:iam::531026255426:role/pulumi-cloud
            # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2  # or your preferred region
      # - run: npm install
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: knose/dev # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}